import type {
  User,
  Project,
  Taak,
  Urenregistratie,
  Werkbon,
  Dagrapport,
  Foto,
  Incident,
  MaterieelItem,
  Notification,
} from "@/types";

export const users: User[] = [
  {
    id: "u-1",
    name: "Sander de Vries",
    email: "sander@jhm.nl",
    role: "directie",
    phone: "+31 6 12 34 56 78",
    certificaten: ["VCA VOL", "BHV"],
    vca_geldig_tot: "2027-04-30",
  },
  {
    id: "u-2",
    name: "Lisa Hendriks",
    email: "lisa@jhm.nl",
    role: "projectleider",
    phone: "+31 6 23 45 67 89",
    certificaten: ["VCA VOL"],
    vca_geldig_tot: "2026-11-12",
  },
  {
    id: "u-3",
    name: "Marco Janssen",
    email: "marco@jhm.nl",
    role: "buitendienst",
    certificaten: ["VCA Basis", "Heftruck"],
    vca_geldig_tot: "2026-09-01",
  },
  {
    id: "u-4",
    name: "Erik van Dijk",
    email: "erik@jhm.nl",
    role: "buitendienst",
    certificaten: ["VCA Basis"],
    vca_geldig_tot: "2026-06-20",
  },
  {
    id: "u-5",
    name: "Yusuf Demir",
    email: "yusuf@jhm.nl",
    role: "buitendienst",
    certificaten: ["VCA Basis", "Hoogwerker"],
    vca_geldig_tot: "2027-02-15",
  },
  {
    id: "u-6",
    name: "Karim El Idrissi",
    email: "karim@jhm.nl",
    role: "buitendienst",
    certificaten: ["VCA Basis"],
    vca_geldig_tot: "2026-08-04",
  },
  {
    id: "u-7",
    name: "Anouk Bakker",
    email: "anouk@jhm.nl",
    role: "kantoor",
  },
];

const today = new Date();
const iso = (d: Date) => d.toISOString();
const daysFromNow = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return iso(d);
};

export const projects: Project[] = [
  {
    id: "p-1",
    nummer: "2026-031",
    naam: "Riolering vervangen Kerkstraat",
    klant: "Gemeente Utrecht",
    adres: "Kerkstraat 12-44",
    plaats: "Utrecht",
    status: "in_uitvoering",
    start_datum: daysFromNow(-12),
    eind_datum: daysFromNow(7),
    voortgang: 68,
    budget_uren: 480,
    geschreven_uren: 326,
    projectleider_id: "u-2",
    team_ids: ["u-3", "u-4", "u-5"],
    beschrijving:
      "Vervangen van hoofdriool over 220 meter, inclusief huisaansluitingen, kolken en herstel straatwerk.",
    laatste_update: daysFromNow(-0.1),
  },
  {
    id: "p-2",
    nummer: "2026-029",
    naam: "Aanleg parkeerterrein Bedrijvenpark Noord",
    klant: "Heijmans Vastgoed",
    adres: "Industrieweg 88",
    plaats: "Amersfoort",
    status: "in_uitvoering",
    start_datum: daysFromNow(-6),
    eind_datum: daysFromNow(21),
    voortgang: 34,
    budget_uren: 720,
    geschreven_uren: 246,
    projectleider_id: "u-2",
    team_ids: ["u-3", "u-6"],
    beschrijving: "Aanleg van 84 parkeerplaatsen, infiltratiekratten en LED-verlichting.",
    laatste_update: daysFromNow(-0.4),
  },
  {
    id: "p-3",
    nummer: "2026-018",
    naam: "Renovatie schoolplein De Werveling",
    klant: "Stichting Onderwijs Eemland",
    adres: "Schoolweg 4",
    plaats: "Soest",
    status: "opgeleverd",
    start_datum: daysFromNow(-44),
    eind_datum: daysFromNow(-3),
    voortgang: 100,
    budget_uren: 320,
    geschreven_uren: 304,
    projectleider_id: "u-2",
    team_ids: ["u-4", "u-5"],
  },
  {
    id: "p-4",
    nummer: "2026-038",
    naam: "Installatie laadpalen kantoorpand",
    klant: "Vesteda",
    adres: "Stadhuisplein 30",
    plaats: "Eindhoven",
    status: "gepland",
    start_datum: daysFromNow(10),
    eind_datum: daysFromNow(24),
    voortgang: 0,
    budget_uren: 180,
    geschreven_uren: 0,
    projectleider_id: "u-2",
    team_ids: ["u-6", "u-5"],
  },
  {
    id: "p-5",
    nummer: "2026-035",
    naam: "Onderhoud groenstrook A28",
    klant: "Rijkswaterstaat",
    adres: "Knooppunt Hoevelaken",
    plaats: "Hoevelaken",
    status: "offerte",
    start_datum: daysFromNow(28),
    eind_datum: daysFromNow(60),
    voortgang: 0,
    budget_uren: 540,
    geschreven_uren: 0,
    projectleider_id: "u-2",
    team_ids: [],
  },
  {
    id: "p-6",
    nummer: "2026-022",
    naam: "Bestrating winkelcentrum De Kraak",
    klant: "Vastned Retail",
    adres: "Marktplein 1-22",
    plaats: "Apeldoorn",
    status: "gepauzeerd",
    start_datum: daysFromNow(-18),
    eind_datum: daysFromNow(14),
    voortgang: 52,
    budget_uren: 410,
    geschreven_uren: 218,
    projectleider_id: "u-2",
    team_ids: ["u-3"],
    laatste_update: daysFromNow(-2.1),
  },
];

export const taken: Taak[] = [
  {
    id: "t-1",
    project_id: "p-1",
    titel: "Verdiepen sleuf 120m³ Noord-zijde",
    toegewezen_aan: ["u-3", "u-4"],
    datum: daysFromNow(0).slice(0, 10),
    begin_tijd: "07:00",
    eind_tijd: "15:30",
    status: "bezig",
    locatie: "Kerkstraat 22, Utrecht",
  },
  {
    id: "t-2",
    project_id: "p-1",
    titel: "Aansluiten 4 huisaansluitingen",
    toegewezen_aan: ["u-5"],
    datum: daysFromNow(0).slice(0, 10),
    begin_tijd: "08:00",
    eind_tijd: "16:00",
    status: "bezig",
    locatie: "Kerkstraat 30, Utrecht",
  },
  {
    id: "t-3",
    project_id: "p-2",
    titel: "Stellen kantopsluitingen vak A",
    toegewezen_aan: ["u-6", "u-3"],
    datum: daysFromNow(0).slice(0, 10),
    begin_tijd: "07:30",
    eind_tijd: "16:00",
    status: "nieuw",
    locatie: "Industrieweg 88, Amersfoort",
  },
  {
    id: "t-4",
    project_id: "p-2",
    titel: "Inmeten infiltratiekratten",
    toegewezen_aan: ["u-5"],
    datum: daysFromNow(1).slice(0, 10),
    status: "nieuw",
  },
  {
    id: "t-5",
    project_id: "p-1",
    titel: "Probleem: stroomkabel onbekend in sleuf",
    toegewezen_aan: ["u-3"],
    datum: daysFromNow(-0.5).slice(0, 10),
    status: "probleem",
    beschrijving: "Onbekende kabel aangetroffen op 1,2m diepte. Werk opgeschort.",
  },
];

export const uren: Urenregistratie[] = [
  { id: "h-1", user_id: "u-3", project_id: "p-1", datum: daysFromNow(-1).slice(0,10), uren: 8.5, type: "regulier", goedgekeurd: true },
  { id: "h-2", user_id: "u-4", project_id: "p-1", datum: daysFromNow(-1).slice(0,10), uren: 8.5, type: "regulier", goedgekeurd: true },
  { id: "h-3", user_id: "u-5", project_id: "p-1", datum: daysFromNow(-1).slice(0,10), uren: 9.0, type: "overuren", goedgekeurd: false },
  { id: "h-4", user_id: "u-6", project_id: "p-2", datum: daysFromNow(-1).slice(0,10), uren: 8.0, type: "regulier", goedgekeurd: true },
  { id: "h-5", user_id: "u-3", project_id: "p-2", datum: daysFromNow(-2).slice(0,10), uren: 8.0, type: "regulier", goedgekeurd: true },
  { id: "h-6", user_id: "u-5", project_id: "p-2", datum: daysFromNow(-2).slice(0,10), uren: 8.5, type: "regulier", goedgekeurd: false },
  { id: "h-7", user_id: "u-4", project_id: "p-3", datum: daysFromNow(-4).slice(0,10), uren: 7.5, type: "regulier", goedgekeurd: true },
];

export const werkbonnen: Werkbon[] = [
  {
    id: "wb-1",
    nummer: "WB-2026-0142",
    project_id: "p-1",
    datum: daysFromNow(-1).slice(0,10),
    uitvoerder_id: "u-3",
    omschrijving: "Sleuf gegraven 24m, riool gelegd Ø250, deksels gesteld.",
    materialen: [
      { naam: "PVC buis Ø250", aantal: 24, eenheid: "m" },
      { naam: "Aansluitstuk 45°", aantal: 4, eenheid: "st" },
      { naam: "Stelmortel", aantal: 6, eenheid: "zak" },
    ],
    uren: 17.0,
    status: "ingediend",
  },
  {
    id: "wb-2",
    nummer: "WB-2026-0141",
    project_id: "p-2",
    datum: daysFromNow(-2).slice(0,10),
    uitvoerder_id: "u-6",
    omschrijving: "Zandbed aangebracht 380m², getrild en geprofileerd.",
    uren: 16.5,
    status: "akkoord_klant",
  },
  {
    id: "wb-3",
    nummer: "WB-2026-0140",
    project_id: "p-3",
    datum: daysFromNow(-4).slice(0,10),
    uitvoerder_id: "u-4",
    omschrijving: "Eindoplevering schoolplein, speeltoestellen geborgd.",
    uren: 7.5,
    status: "akkoord_klant",
  },
];

export const dagrapporten: Dagrapport[] = [
  {
    id: "dr-1",
    project_id: "p-1",
    user_id: "u-3",
    datum: daysFromNow(-1).slice(0,10),
    stemming: "neutraal",
    uitgevoerd: "Sleuf 24m verdiept en eerste 12m buis gelegd. Verkeer omgeleid via Korte Steeg.",
    belemmeringen: "Onbekende kabel om 14:10 — werk stilgelegd, KLIC-melding opnieuw opgevraagd.",
    morgen: "Doorgaan met buis vanaf put 3 en starten met aansluiting nr. 22.",
    fotos_count: 14,
    ai_samenvatting:
      "Goede dagproductie tot 14:10. Vondst van onbekende kabel veroorzaakt korte stagnatie; gemeld aan projectleiding. Vervolgplan voor morgen helder.",
  },
  {
    id: "dr-2",
    project_id: "p-2",
    user_id: "u-6",
    datum: daysFromNow(-1).slice(0,10),
    stemming: "goed",
    uitgevoerd: "Zandbed 380m² afgewerkt, materiaal geleverd, kraan gepositioneerd voor morgen.",
    morgen: "Stellen kantopsluitingen vak A.",
    fotos_count: 8,
  },
];

export const fotos: Foto[] = Array.from({ length: 24 }).map((_, i) => ({
  id: `f-${i + 1}`,
  project_id: i % 3 === 0 ? "p-2" : "p-1",
  user_id: i % 2 === 0 ? "u-3" : "u-5",
  url: `https://picsum.photos/seed/jhm-${i + 1}/640/480`,
  type: (["voortgang", "oplevering", "schade", "veiligheid"] as const)[i % 4],
  taken_at: daysFromNow(-Math.floor(i / 2)),
  bijschrift: i % 4 === 0 ? "Sleuf na storten zandbed" : undefined,
}));

export const incidenten: Incident[] = [
  {
    id: "inc-1",
    project_id: "p-1",
    type: "onveilig",
    prioriteit: "hoog",
    status: "in_behandeling",
    melder_id: "u-3",
    verantwoordelijke_id: "u-2",
    beschrijving: "Onbekende stroomkabel aangetroffen in sleuf op 1,2m diepte.",
    fotos: ["https://picsum.photos/seed/inc-1a/640/480"],
    datum: daysFromNow(-0.5),
  },
  {
    id: "inc-2",
    project_id: "p-2",
    type: "schade",
    prioriteit: "midden",
    status: "open",
    melder_id: "u-6",
    beschrijving: "Bermbeschadiging door rupskraan, lengte ca. 4m.",
    fotos: ["https://picsum.photos/seed/inc-2a/640/480"],
    datum: daysFromNow(-1.2),
  },
  {
    id: "inc-3",
    type: "klacht",
    prioriteit: "laag",
    status: "gesloten",
    melder_id: "u-7",
    beschrijving: "Buurtbewoner over geluidsoverlast vroeg in de ochtend; gesproken en afgestemd.",
    fotos: [],
    datum: daysFromNow(-3),
    project_id: "p-1",
  },
];

export const materieel: MaterieelItem[] = [
  { id: "m-1", type: "voertuig", naam: "Iveco Daily L3H2", identifier: "VK-123-J", status: "in_gebruik", toegewezen_aan: "u-3", toegewezen_project_id: "p-1", apk_tot: "2026-11-04" },
  { id: "m-2", type: "voertuig", naam: "Volkswagen Crafter", identifier: "GH-44-FK", status: "in_gebruik", toegewezen_aan: "u-6", toegewezen_project_id: "p-2", apk_tot: "2027-02-10" },
  { id: "m-3", type: "aanhanger", naam: "Hapert kipper 3500", identifier: "WB-22-NN", status: "beschikbaar", apk_tot: "2026-07-19" },
  { id: "m-4", type: "gereedschap", naam: "Wacker trilplaat 200kg", identifier: "TR-014", status: "in_gebruik", toegewezen_aan: "u-3" },
  { id: "m-5", type: "gereedschap", naam: "Hilti TE 60", identifier: "HIL-203", status: "onderhoud" },
  { id: "m-6", type: "meetapparatuur", naam: "Leica GPS rover", identifier: "LE-002", status: "beschikbaar", laatste_keuring: "2026-03-12" },
  { id: "m-7", type: "sleutel", naam: "Sleutelset Werf Amersfoort", identifier: "K-AMS-12", status: "in_gebruik", toegewezen_aan: "u-2" },
];

export const notifications: Notification[] = [
  {
    id: "n-1",
    to_user_id: "u-2",
    titel: "Probleemmelding op project 2026-031",
    body: "Marco meldt een onbekende kabel in de sleuf — werk opgeschort.",
    type: "incident",
    read: false,
    created_at: daysFromNow(-0.5),
    link: "/projecten/p-1",
  },
  {
    id: "n-2",
    to_user_id: "u-2",
    titel: "Werkbon WB-2026-0142 wacht op goedkeuring",
    body: "Ingediend door Marco voor project Kerkstraat.",
    type: "actie",
    read: false,
    created_at: daysFromNow(-1),
  },
  {
    id: "n-3",
    to_user_id: "u-2",
    titel: "Foto-upload voltooid",
    body: "14 foto's gekoppeld aan dagrapport van Kerkstraat.",
    type: "info",
    read: true,
    created_at: daysFromNow(-1.1),
  },
];

// Helpers
export const findUser = (id?: string) => users.find((u) => u.id === id);
export const findProject = (id?: string) => projects.find((p) => p.id === id);
